markdownEd/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("markdown/", include("markdown_app.urls"))
]

markdown_app/urls.py
from django.urls import path

from . import views
from . import api_view

app_name = "markdown_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("submit", api_view.submit, name="submit"),
    path("file/<int:fileID>", views.file, name="file"),
    path("file/preview/<int:fileID>", views.filePreview, name="file_preview"),
    path("api/file/<int:fileID>/<str:userName>", api_view.getFile, name="api_file"),
    path("api/create_file", api_view.createFile, name="api_create_file"),
    path("api/active_user", api_view.getActiveEditors, name="api_active_user"),
    path(
        "api/change_file_name",
        api_view.changeFileName,
        name="api_change_file_name",
    ),
    path(
        "api/delete_file",
        api_view.deleteFile,
        name="api_delete_file",
    ),
]

markdown_app/models.py
from django.db import models

# Create your models here.

## TODO: Expir Time 5 seconds
expireTime = 5


class Markdown(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    version = models.IntegerField(blank=True, null=True)

    def __str__(self) -> str:
        return self.title


class Record(models.Model):
    user = models.CharField(max_length=100, blank=True, null=True)
    markdownID = models.IntegerField()
    time = models.DateTimeField()
    pass

markdown_app/views.py
from django.shortcuts import render

# from django.http import HttpResponse

from .models import Markdown

# Create your views here.


def index(request):
    """
    Show all the existing files
    """
    all = Markdown.objects.all()
    context = {"all": all}

    return render(request, "markdown_app/all.html", context=context)


def file(request, fileID):
    m = Markdown.objects.get(id=fileID)
    context = {}
    context["file"] = m.text
    context["title"] = m.title
    context["id"] = m.id
    context["version"] = m.version
    return render(request, "markdown_app/file.html", context=context)


def filePreview(request, fileID):
    m = Markdown.objects.get(id=fileID)
    context = {}
    context["file"] = m.text
    context["title"] = m.title
    context["id"] = m.id
    context["version"] = m.version
    return render(request, "markdown_app/file_preview.html", context=context)

markdown_app/templates/markdown_app/all.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Markdown Editor</title>
        {% load static %}
        <link rel="icon" type="image/x-icon"
            href="{% static 'markdown_app/favicon.ico' %}">
        <script src="{% static 'markdown_app/jquery.min.js' %}"></script>
    </head>

    <body>

        <div>
            <h1>Markdown Editor</h1>
            <p> Welcome to Markdown Editor.
            </p>
            <p>To change your name, please input value in 'Your name' and click
                on 'change'.</p>
            <p>To add a new file, please input value in 'File Name' and click on
                'Add File' button.</p>
        </div>
        {% csrf_token %}
        <div>
            Your name : <input id="name" value>
            <button onclick="setNameToCookie()">change</button>
        </div>
        <br>
        <div>
            File Name : <input id="filename" value>
            <button onclick="addFile()">Add File</button>
        </div>
        <br>

        <div>
            <table cellpadding="0" cellspacing="20">
                <tr>
                    <td>File Name</td>
                    <td></td>
                    <td>Editing User</td>
                </tr>
                {% for x in all %}
                <tr>
                    <td><a
                            href="{% url 'markdown_app:file_preview' x.id %}">{{x.title}}</a></td>
                    <td> <button onclick="changeName('{{x.id}}')">change
                            name</button> <button
                            onclick="deleteFile('{{x.id}}')">delete</button>
                    </td>
                    <td id="file{{x.id}}" class="file"></td>
                </tr>
                {% endfor %}
            </table>

        </div>

        <script src="{% static 'markdown_app/all.js' %}"></script>
        <script>

        const data = {
            csrftoken: document.querySelector('[name=csrfmiddlewaretoken]').value,
            createFileURL: "{% url 'markdown_app:api_create_file' %}",
            newFileURLTemplate: "{% url 'markdown_app:file_preview' 0 %}",
            userAPI: "{% url 'markdown_app:api_active_user' %}",
            changeFileURL: "{% url 'markdown_app:api_change_file_name' %}",
            deleteFileURL: "{% url 'markdown_app:api_delete_file' %}",
        }

        updateEditingUser();
        document.getElementById("name").value = getNameFromCookie()
        $(function () {
            setInterval(updateEditingUser, 3000)
        });

    </script>

    </body>

</html>

markdown_app/templates/markdown_app/file.html
<!DOCTYPE html>
<html lang="zh">

<head>
    <meta charset="utf-8" />
    <title>Simple example - Editor.md examples</title>
    {% load static %}
    {% include 'markdown_app/layout/load_head.html' %}
    <link rel="icon" type="image/x-icon" href="{% static 'markdown_app/favicon.ico' %}">
</head>

<body>

    {% csrf_token %}

    <div>
        <div id="else">
            <div style="width: 100%; text-align: center; position: absolute;">
                <div id="successAlert" class="alert alert-success alert-dismissible fade" role="alert"
                    style="width: 50%; margin: 0 auto;">
                    Your modification is saved
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
            <div class="container-fluid">
                <header>
                    <h1 id="title">{{ title }}</h1>
                </header>

                <button type="button" class="btn btn-primary" onclick="submit()">SAVE</button>
                <button type="button" class="btn btn-primary" onclick="preview()">Preview</button>
                <button type="button" class="btn btn-primary" onclick="menu()">Menu</button>
                <strong>Editing User: </strong> <strong id="editingUser">a</strong>
            </div>
        </div>
        <div id="test-editormd">
            <textarea style="display:none;">{{ file }}</textarea>
        </div>
    </div>
    {% include 'markdown_app/layout/load_foot.html' %}
    <script src="{% static 'markdown_app/file.js' %}"></script>
    <script type="text/javascript">
        const data = {
            testEditor: null,
            submitURL: "{% url 'markdown_app:submit' %}",
            fileID: "{{id}}",
            FileApiURL: "{% url 'markdown_app:api_file' id 'anonymous' %}",
            previewURL: "{% url 'markdown_app:file_preview' id  %}",
            MenuURL: "{% url 'markdown_app:index' %}",
            version: "{{version}}",
            csrftoken: document.querySelector('[name=csrfmiddlewaretoken]').value,
            set verSet(version) {
                this.version = version
            },
            set editorSet(editormd) {
                this.testEditor = editormd;
            },
            set FileApiSet(url) {
                this.FileApiURL = url
            }
        }

        // replace the anonymous with the name given in the cookie 
        function getNameFromCookie() {
            var cname = "name"
            var name = cname + "=";
            var ca = document.cookie.split(';');
            for (var i = 0; i < ca.length; i++) {
                var c = ca[i].trim();
                if (c.indexOf(name) == 0) return c.substring(name.length, c.length);
            }
            return "annoynomous";
        }

        data.FileApiSet = data.FileApiURL.replace("anonymous", getNameFromCookie())

        console.log(data.FileApiURL)


        $(function () {
            data.editorSet = editormd("test-editormd", {
                width: "100%",
                height: window.innerHeight - $("#else").innerHeight() - 20,
                syncScrolling: "single",
                path: "{% static 'markdown_app/lib/' %}",
                tex: true
            });

        });
        // add a on zoom event listener
        window.addEventListener("resize", watchWindowSize);
        function watchWindowSize() {
            data.testEditor.height(window.innerHeight - $("#else").innerHeight() - 20)
        }

        getFileAndUpdate()
        // periodically update the file with the post
        $(function () {
            setInterval(getFileAndUpdate, 1000)
        });

        window.addEventListener("beforeunload", function (e) {

            //TODO: check the saving mechanism

            submit()
            // var confirmationMessage = 'It looks like you have been editing something. '
            //     + 'If you leave before saving, your changes will be lost.';

            // (e || window.event).returnValue = confirmationMessage; //Gecko + IE
            // return confirmationMessage; //Gecko + Webkit, Safari, Chrome etc.
        });


    </script>
    <script src="{% static 'markdown_app/en.js' %}"></script>
</body>

</html>

markdown_app/templates/markdown_app/file_preview.html
<!DOCTYPE html>
<html lang="zh">

<head>
    <meta charset="utf-8" />
    <title>Simple example - Editor.md examples</title>
    {% load static %}
    {% include 'markdown_app/layout/load_head.html' %}
    <link rel="stylesheet" href="{% static 'markdown_app/editormd.preview.css' %}" />
    <link rel="icon" type="image/x-icon" href="{% static 'markdown_app/favicon.ico' %}">
</head>

<body>
    <style>
        #sidebar {
            /* width: 20%; */
            height: 100%;
            position: fixed;
            top: 0;
            right: 0;
            overflow: hidden;
            background: #fff;
            z-index: 100;
            padding: 18px;
            border: 1px solid #ddd;
            border-top: none;
            border-bottom: none;
        }

        #sidebar:hover {
            overflow: auto;
        }

        #sidebar h1 {
            font-size: 16px;
        }
    </style>

    {% csrf_token %}

    <div>
        <div id="else">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10">
                        <header style="padding-left: 20px;">
                            <h1 id="title">{{ title }}</h1>
                        </header>
                        <div id="test-editormd">
                            <textarea style="display:none;">{{ file }}</textarea>
                        </div>
                    </div>
                    <div class="col-md-2"
                        style="border: 1px solid #ddd;border-top: none;border-bottom: none; border-right: none;">
                        <!-- <div id="sidebar"> -->
                        <button type="button" class="btn btn-primary" onclick="edit()">Edit</button>
                        <button type="button" class="btn btn-primary" onclick="menu()">Menu</button>
                        <div class="markdown-body editormd-preview-container" id="custom-toc-container"></div>
                        <!-- </div> -->
                    </div>


                </div>



            </div>
        </div>

    </div>
    <script src="{% static 'markdown_app/jquery.min.js' %}"></script>
    <script src="{% static 'markdown_app/lib/marked.min.js' %}"></script>
    <script src="{% static 'markdown_app/lib/prettify.min.js' %}"></script>

    <script src="{% static 'markdown_app/lib/raphael.min.js' %}"></script>
    <script src="{% static 'markdown_app/lib/underscore.min.js' %}"></script>
    <script src="{% static 'markdown_app/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'markdown_app/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'markdown_app/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'markdown_app/file_preview.js' %}"></script>

    <script src="{% static 'markdown_app/editormd.js' %}"></script>

    <script type="text/javascript">
        var testEditormdView2;
        const data = {
            testEditor: null,
            submitURL: "{% url 'markdown_app:submit' %}",
            fileID: "{{id}}",
            FileEditURL: "{% url 'markdown_app:file' id %}",
            FileApiURL: "{% url 'markdown_app:api_file' id '__' %}",
            MenuURL: "{% url 'markdown_app:index' %}",
            version: "{{version}}",
            csrftoken: document.querySelector('[name=csrfmiddlewaretoken]').value,
            set verSet(version) {
                this.version = version
            },
            set editorSet(editormd) {
                this.testEditor = editormd;
            }
        }

        $(function () {
            data.editorSet = editormd.markdownToHTML("test-editormd", {
                htmlDecode: "style,script,iframe",  // you can filter tags decode
                toc: true,
                tocm: true,    // Using [TOCM]
                tocContainer: "#custom-toc-container",
                emoji: true,
                taskList: true,
                tex: true,  // 默认不解析
                flowChart: true,  // 默认不解析
                sequenceDiagram: true,  // 默认不解析
            });

        });
        // add a on zoom event listener
        window.addEventListener("resize", watchWindowSize);
        function watchWindowSize() {
            data.testEditor.height(window.innerHeight - $("#else").innerHeight() - 20)
        }

        getFileAndUpdate()
        // periodically update the file with the post
        $(function () {
            setInterval(getFileAndUpdate, 3000)
        });


    </script>
    <script src="{% static 'markdown_app/en.js' %}"></script>
</body>

</html>

markdown_app/templates/markdown_app/layout/load_foot.html
{% load static %}
<script src="{% static 'markdown_app/jquery.min.js' %}"></script>
<script src="{% static 'markdown_app/editormd.js' %}"></script>

markdown_app/templates/markdown_app/layout/load_head.html
{% load static %}
<link rel="stylesheet" href="{% static 'markdown_app/editormd.css' %}" />
<link rel="stylesheet" href="{% static 'markdown_app/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'markdown_app/bootstrap/css/bootstrap.min.css' %}">
<script src="{% static 'markdown_app/bootstrap/js/bootstrap.bundle.min.js' %}"></script>